sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "7"
script:
  - yarn test
after_script:
#  - npm run coveralls:upload
after_success:
  - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
  - python travis_after_all.py
  - 'export $(cat .to_export_back) &> /dev/null'
  - yarn run semantic-release