sudo: false
language: node_js
node_js:
  - '7'
  - '6'
  - '4'
script:
  - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json
  - yarn run semantic-release